### ISSUE TITLE
Error when displaying on page

### ISSUE THREAD

**Issue by Chris-Archer-Upbeat** [systemick3/quicktabs8#1]
Hi,

When the block is on the page I get the following error:

`Notice: Undefined index: display_title in Drupal\quicktabs\Plugin\TabRenderer\QuickTabs->render() (line 106 of modules/quicktabs/src/Plugin/TabRenderer/QuickTabs.php).`

I have two views been referenced with no argument and the views are both pages, with pagers.

**Comment by systemick3** [comment]
Fixed
