### ISSUE TITLE
QuickTabs Not Loading Tab For Anonymous Users

### ISSUE THREAD

**Issue by ColdSunERA** [systemick3/quicktabs8#4]
The default active tab displays correctly on page load for anonymous users. When an anonymous user clicks a different tab, it simply sits on 'loading'.
Ajax being on or off does not rectify the issue.

This issue does not occur when logged in.

To reproduce:
Set Quicktabs to Ajax refresh
Clear Cache
Logout
Attempt to load 2nd Quicktab's tab.
Only see Loading...

**Comment by SGColdSun** [comment]
Error was caused by twig debug code being outputted incorrectly disregard.

**Comment by systemick3** [comment]
Yep a fairly major bug. Fixed now though.
