### ISSUE TITLE
Inquiry - Page Support?

### ISSUE THREAD

**Issue by cas-old** [systemick3/quicktabs8#5]
Hi!

This is more of an inquiry than issue, are you planning to push this into a content type addition/field rather than block use in the future? For places that are heavily using this module on Drupal 7, it doesn't seem like blocks would be the way to go, as this will clutter their block page.  Might be easier to organize and filter this way too.

**Comment by ColdSunERA** [comment]
If someone wants to keep the block page clean, they can always render the blocks in the template file.

**Comment by cas-old** [comment]
Alright thanks! I may give it a try.
I'm learning the development side of things, so I'll give it a go and see if I can figure it out.  :)
