### ISSUE TITLE
can't choose "none" for default tab

### ISSUE THREAD

**Issue by ghost** [systemick3/quicktabs8#6]
When I attempt to select "none" for the default tab when using the Accordion renderer, it says my changes have been saved but it switches the default to the first tab. I have "collapsible" checked and I'd like all of the tabs to collapsed by default. Is that possible? If not, "none" really shouldn't be a selectable option.

**Comment by systemick3** [comment]
Accordion tabs now able to open without a default tab ie no tab displaying by selecting 'None' on options form. All other renderers default to first tab.

**Comment by ghost** [comment]
Thanks for that! Works as you said.
